telegram:
  token: ""
  debug: false
  timeout: 60

ollama:
  base_url: "http://localhost:11434"
  model: "llama3"
  temperature: 0.7
  max_tokens: 800
  # Таймаут для генерации ответа (в секундах)
  timeout: 60

storage:
  type: "memory"
  memory:
    cleanup_interval: 30m
    ttl: 24h
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

logger:
  level: "info"
  format: "json"